### ISSUE TITLE
Shell panic on malformed find command: 'byte index is out of bounds'

### ISSUE THREAD

**Issue by fourohfour** [redox-os/ion#367] opened 2017-07-06 19:47 UTC
**Reproduction**: Running the command `find "./[.]*"` in ion shell causes a panic.

**Expected behavior**: A reasonable error message. 

**Actual behavior**: Shell aborts with the following message:

    thread 'main' panicked at 'byte index 9 is out of bounds of `"./[.]*"`', /checkout/src/libcore/str/mod.rs:2133:8
    note: Run with `RUST_BACKTRACE=1` for a backtrace.
    Aborted (core dumped)

**Build information**:

    ion-shell v1.0.3

    Ubuntu 14.04.5 LTS

--------

**Comment by huntergoldstein** [comment] 2017-07-07 01:56
What is the output of `git rev-parse HEAD`? I don't see this behavior on `9d5cb19`

**Comment by mmstick** [comment] 2017-07-15 22:02
Closing as I can't reproduce it either.

**Closed by mmstick** 2017-07-15 22:02 UTC
Labels: bug

**Comment by fourohfour** [comment] 2017-07-15 23:28
Apologies for not responding to this quicker. I was away from my Linux system.

I rebuilt from a fresh `git clone` and did not encounter the same issue again. The issue must have been isolated to a specific build.
