### ISSUE TITLE
su doesn't work very well from inside ion

### ISSUE THREAD

**Issue by jsalzbergedu** [redox-os/ion#595] opened 2017-11-18 15:43 UTC
**Reproduction**: [describe how you are able to reproduce ("trigger") this bug/issue.]

Use su from ion (not bash).

**Expected behavior**: [describe the behavior you would expect the repro to yield.]

Su runs as it does in bash, perhaps dropping from the ion shell to the bash shell.

**Actual behavior**: [describe the actual behavior, which is presented through the repro.].

Su drops into bash, but does not display lines as they are typed.

**Misc**: [optional: for other relevant information that should be known or cannot be described in the other fields.]

If you run `bash` then `su`, it works as expected.

**Comment by mmstick** [comment] 2017-11-19 01:13
Not able to reproduce on my end. Am using Solus OS, with:

```
Linux mmstick-laptop 4.13.13-33.current #1 SMP Thu Nov 16 19:49:20 UTC 2017 x86_64 GNU/Linux
```

**Comment by jsalzbergedu** [comment] 2017-11-19 01:49
Oddly enough, the issue went away for me as well. FWIW, the issue popped up when I was in `/sys/class/backlight/intel_backlight`, but I can't get it to happen again. Should I close the issue or keep it open for some time?

**Comment by mmstick** [comment] 2017-11-19 02:57
You can close it, and reopen if you experience something similar.

**Closed** 2017-11-19 03:00 UTC
