### ISSUE TITLE
Manual should be accessible without running a local webserver

### ISSUE THREAD

**Issue by fwrs** [redox-os/ion#509] opened 2017-08-21 10:27 UTC
The only way to access the formatted manual is cruel, requiring a person to compile additional software (with 90 dependencies). I think you should host pre-compiled documentation on your servers or provide manpages for Linux.

**Comment by mmstick** [comment] 2017-08-21 17:02
Cruel? 90 dependencies? That's a bit of an exaggeration.

```sh
cargo install mdbook
mdbook serve
firefox http://localhost:3000/
```

That's all it takes.

**Comment by fwrs** [comment] 2017-08-22 14:22
Don't you think your response is selfish?

**Comment by jackpot51** [comment] 2017-08-22 19:44
@fwrs Selfish and cruel is asking for others to take on an additional task that benefits yourself. That is what you are doing.

**Comment by mmstick** [comment] 2017-08-22 20:12
You can access the documentation right here on GitHub if you don't want to install mdBook. If you do build it with mdBook, the generated book consists of static assets that you can look at by just opening the index HTML page with your web browser. But it's more convenient to let mdBook serve it on a local port.

The book is still in it's early stages, so I don't think there's a need to host it anywhere just yet. But I have been thinking about implementing a means of provided the generated HTML alongside packaged builds of Ion, and having a built-in command that just serves to open the index page with the system's default web browser.

**Comment by BafDyce** [comment] 2017-08-22 21:38
Just wanted to drop my thoughts too. 

@mmstick I generally agree with you, however

> You can access the documentation right here on GitHub if you don't want to install mdBook.

The problem is that the documentation in the repo is not browsable, as all links refer to .html pages otherwise mdbook cannot create valid links.

> having a built-in command that just serves to open the index page with the system's default web browser

This sounds sweet :)

**Comment by mmstick** [comment] 2017-08-23 05:51
There's now a `setup.ion` script in the repo's root directory. You can install the Ion documentation system-wide via `./setup.ion build docs && ./setup.ion install docs`. Then you enter `ion-docs` in the command line to open the manual with your preferred `BROWSER`. And with that, I will now close this issue.

**Closed by mmstick** 2017-08-23 05:51 UTC

**Comment by jackpot51** [comment] 2017-08-23 15:26
@BafDyce @mmstick @fwrs Here you go: https://doc.redox-os.org/ion-manual/

I still dislike your attitude @fwrs. The manual is regenerated on every Ion master branch commit.

**Comment by fwrs** [comment] 2017-08-24 13:16
Sorry, mdbook takes a while to compile for me
