### ISSUE TITLE
ion doesn't output strings that don't end with a newline

### ISSUE THREAD

**Issue by nivkner** [redox-os/ion#535] opened 2017-09-19 22:48 UTC
**Reproduction**: [describe how you are able to reproduce ("trigger") this bug/issue.]

write this in rust:
```rust
use std::io;
use std::io::prelude::*;

fn main() {
    let mut out = io::stdout();
    write!(out,"hello world").unwrap(); // works when ends with \n
}
```
**Expected behavior**: [describe the behavior you would expect the repro to yield.]

```
# cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.0 secs
     Running `target/debug/output`
hello world#
```

**Actual behavior**: [describe the actual behavior, which is presented through the repro.].

```
# cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.0 secs
     Running `target/debug/output`
#
```

**Build information**: [output of `rustc -V`, `git rev-parse HEAD`, `qemu-i386 -version`, `uname -a`, `ion --version`, etc.]

ion: 1.0.5 (x86_64-unknown-linux-gnu)
rev: 1ac33a9bc288e78df4126fd0a41d3a9c9529192b
linux: 4.12.10-1
rustc: rustc 1.22.0-nightly (d93036a04 2017-09-07)

**Blocking/related**: [issues or PRs blocking or being related to this issue.]

**Misc**: [optional: for other relevant information that should be known or cannot be described in the other fields.]

------

_If the above does not fit the nature of the issue feel free to modify it._

**Comment by mmstick** [comment] 2017-09-19 22:50
Duplicate of https://github.com/redox-os/ion/issues/370

**Closed by mmstick** 2017-09-19 22:50 UTC
