### ISSUE TITLE
Backspace does not work on xterm

### ISSUE THREAD

**Issue by KillTheMule** [redox-os/ion#388] opened 2017-07-10 21:25 UTC
**Reproduction**: [describe how you are able to reproduce ("trigger") this bug/issue.]
Run ion in xterm, type some text. Try Backspace.

**Expected behavior**: [describe the behavior you would expect the repro to yield.]
Deletes backwards.

**Actual behavior**: [describe the actual behavior, which is presented through the repro.].
Does not seem to do anything. I can use `<C-b><C-d>` successfully instead.

**Build information**: [output of `rustc -V`, `git rev-parse HEAD`, `qemu-i386 -version`, `uname -a`, etc.]
Ion version 1.0.4 Alpha, xorg version 7.4, Linux kernel 4.9.0 on gentoo, fvwm 2.6.5.

**Comment by huntergoldstein** [comment] 2017-07-10 21:35
Looks like a bug in `liner` @MovingtoMars; I can reproduce this behavior by running the `liner` sample application in `xterm`.

**Comment by MovingtoMars** [comment] 2017-07-11 00:58
Unable to reproduce on either liner sample or ion.
```
Xorg: Version: 1:7.7+16ubuntu3
Kernel: Linux 4.8.0-53
Xterm: Version: 324-2ubuntu1
```

**Comment by mmstick** [comment] 2017-07-11 01:00
My Linux distribution (SolusOS) doesn't even have xterm available to test with.

**Comment by huntergoldstein** [comment] 2017-07-11 01:30
So the bug appears on my main computer:
```
Xorg Version: 1.19.3
uname -r: 4.11.9-1-ARCH
Xterm: 330
```
BUT not on my netbook (which is running GalliumOS, a modified Ubuntu):
```
Xorg Version: 1:7.7+13ubuntu3-galliumos1
uname -r: 4.9.4-galliumos-braswell
Xterm: 322
```

**Comment by huntergoldstein** [comment] 2017-07-11 02:23
Apparently on Arch Linux (I guess Gentoo as well) `xterm` will send `Ctrl-h` when the backspace key is pressed. I'm going to guess that Ubuntu patches that.

**Comment by KillTheMule** [comment] 2017-07-11 06:01
Terminals are hard. Some info on `Ctrl-h` vs. `BS` can be found at https://github.com/neovim/neovim/issues/2048, although I personally don't understand most of it.

**Comment by mmstick** [comment] 2017-07-12 03:18
Liner was just updated to handle C^h, and I've updated liner, so it should be fixed now.

**Comment by KillTheMule** [comment] 2017-07-12 13:04
Nice :) Can't try before the next release, should I close the issue anyways?

**Comment by mmstick** [comment] 2017-07-13 16:09
I'll close the issue, but if you find out that it still doesn't work, I would re-open it.

**Closed by mmstick** 2017-07-13 16:09 UTC
Labels: bug, liner
