### ISSUE TITLE
Ion needs job control

### ISSUE THREAD

**Issue by skylerberg** [redox-os/ion#29] opened 2016-01-18 03:50 UTC
We need to allow interactive job control. We will need the following commands:
- [x] bg
- [ ] fg (Partially Implemented)
- [x] jobs
- [x] suspend
- [x] disown
- [x] wait
- [x] process groups

**Comment by skylerberg** [comment] 2016-02-13 21:26
https://github.com/redox-os/ion/pull/86

**Comment by skylerberg** [comment] 2016-02-13 21:26
We can now run a task in the background. There is still much work to be done.

**Comment by skylerberg** [comment] 2016-03-08 05:17
Since  the backgrounding was not useful in it's current state and I haven't taken the time to make it work properly with piping, I am removing it. This is not really lost work because I am going to add it back in for pipelines sometime soon. I am also leaving it in the grammar for now. For reference, here is the code I am taking out: https://github.com/redox-os/ion/blob/4a8cd17ec85d1e2a980987c2dda7635291f77653/src/main.rs#L228.

**Comment by mmstick** [comment] 2017-06-22 00:20
This work should be very simple to implement now. We just need a means of storing job thread handles in the shell, and then implement the commands to send signals to these running jobs.

**Comment by mmstick** [comment] 2017-07-01 14:48
SIGINT and SIGTERM are implemented, and process IDs are now stored within the shell.

**Comment by mmstick** [comment] 2017-07-02 03:17
SIGTSTOP is implemented.

**Comment by mmstick** [comment] 2017-07-02 05:54
We now have `fg`, `bg`, `wait`, and `jobs`.

**Comment by mmstick** [comment] 2017-07-02 06:22
I will note, however, that, I observed some strange behavior with the difference between the reported PID by Rust, and the actual PID found in `top`. I had to apply an offset based on how a process is getting sent to the background. A command like `command args... &` would get a PID that's off by 2 of the actual PID, whereas `command args...` would have a PID that's off by 1. If anyone can figure out why that is, I'd like to know.

**Comment by myfreeweb** [comment] 2017-07-02 14:55
I'm happy that ion is finally getting job control… however it's not really there yet.

First, don't hardcode SIGTSTP as 20. It's not 20 on FreeBSD, for example. Use the constant from `libc`/`nix`.

Second, seems like the entire TSTP handling thing is wrong :( That's not how other shells do it.

Currently just suspending vim inside ion that was started from zsh returns… back to the zsh.

You should use process groups, [pass around control of the terminal with tcsetpgrp](https://github.com/xonsh/xonsh/blob/26b0340d7081c25764b633c214b283186d550ddd/xonsh/jobs.py#L135-L161), [wait for child's stop with the `WUNTRACED` waitpid flag](https://github.com/xonsh/xonsh/blob/26b0340d7081c25764b633c214b283186d550ddd/xonsh/jobs.py#L176)…

I'm trying to implement this in https://github.com/myfreeweb/ion — currently fg doesn't work correctly… someone with more arcane unix knowledge should look at this :D

**Comment by mmstick** [comment] 2017-07-02 15:53
@myfreeweb 

> Second, seems like the entire TSTP handling thing is wrong :( That's not how other shells do it.

Are you sure about that? Listening to SIGTSTP and then sending SIGTSTP/SIGCONT to child processes is exactly what the documentation in other shells states that they are doing. It's at least working perfectly on Linux.

> Currently just suspending vim inside ion that was started from zsh returns… back to the zsh.

That's not what's happening here on Linux. If I launch nvim from ion from bash, it returns to ion. If it's returning to zsh, it's because Ion isn't listening to SIGTSTP (likely as you said, the signal is not 20 like on Linux).

**Comment by myfreeweb** [comment] 2017-07-02 16:06
Yeah, if I only fix the signal number, it returns to ion. But then fg doesn't work.

Oh wait — it does work if I just add `- 1` to the pid where it's sending SIGCONT.

I'll send a pull request that only fixes this for now.

> the documentation in other shells states that they are doing

well, they might be doing that too, but pretty much all of them use process groups and `tcsetpgrp`. I linked to xonsh already. [Here's fish](https://github.com/fish-shell/fish-shell/blob/7904f92c9ec4966cfb2637f8d2b17bb855245541/src/proc.cpp#L780-L827).

I think the reason for the process group stuff is that if the process forks itself and the original dies, you end up with a different PID, and the shell will try to suspend the wrong PID!

**Comment by mmstick** [comment] 2017-07-02 16:16
Do you want to investigate implementing process groups? Or shall I do that?

**Comment by myfreeweb** [comment] 2017-07-02 16:26
I've [tried](https://github.com/myfreeweb/ion/commit/ed036960c5cfbcf9b6b24319da4e749ac420f59b)… didn't fully succeed yet

**Comment by myfreeweb** [comment] 2017-07-02 17:48
oh also just found another reason why process groups are necessary. sudo. Like if I run `sudo pacman -Suy`, Ctrl+Z and fg, it doesn't return the terminal to pacman, it returns to sudo which is useless

**Comment by mmstick** [comment] 2017-07-04 23:49
I'll have support for handling process groups shortly.

**Comment by mmstick** [comment] 2017-07-05 16:29
Gradually getting there. I believe all I have left to do now is figure out the `tcgetattr` and `tcsetattr` functions, and properly implement the `fg` command.

**Comment by mmstick** [comment] 2017-07-06 18:54
There's only one issue that I have right now. C-c works, but C-z does not work at all. I've removed the usage of the `wait` and `wait_try` functions from the `std` and am using `waitpid` instead to monitor foreground processes by their IDs. Only problem is that while `waitpid` is notified when the process exited via C-c or exited in general, it is not notified at all when the process receives a `SIGTSTP`, even though I'm listening for the `WaitStatus::Stopped` signal. A bit confusing, but will keep trying.

**Comment by myfreeweb** [comment] 2017-07-06 21:20
You pass `None` to waitpid, you need the `WUNTRACED` flag. Look at my code again https://github.com/myfreeweb/ion/commit/ed036960c5cfbcf9b6b24319da4e749ac420f59b#diff-cc20bc374fba8d873a99948f7710250eR233

**Comment by mmstick** [comment] 2017-07-06 21:29
That did it. I'll clean up / refactor my code and push the changes soon.

**Comment by mmstick** [comment] 2017-07-06 23:31
Trying to get `fg` working properly at the moment, and then I need to fix up the Redox side of things.

**Comment by mmstick** [comment] 2017-07-07 01:08
I just landed all the changes I've worked on thus far. Just having an issue with the `fg` command not working properly. It may have to be because I have a background thread monitoring background processes with `waitpid`, and that is conflicting with the `fg` command trying to listen to the same process with `waitpid` at the same time.

**Comment by myfreeweb** [comment] 2017-07-07 11:25
You need to mask some signals when doing `tcsetpgrp`! https://github.com/myfreeweb/ion/blob/ed036960c5cfbcf9b6b24319da4e749ac420f59b/src/shell/pipe.rs#L215-L224

I see you have `mask_sigstp`, for some reason it's in `main` and it's not using the nice `nix` `SigSet` API…

**Comment by mmstick** [comment] 2017-07-07 19:38
Recommendation for designing job control in shells is for the parent shell to ignore/block signals during shell initialization, at the beginning of the program, and only unblock these signals in child forks. [Following this guide](https://www.gnu.org/software/libc/manual/html_node/Initializing-the-Shell.html#Initializing-the-Shell). Although I should mask more than just `SIGTSTP` I suppose.

**Comment by mmstick** [comment] 2017-07-07 19:39
But I think the `waitpid` option is caused by the background process already being reaped in another thread, where it's normal to receive an `ECHILD` response.

**Comment by mmstick** [comment] 2017-07-08 20:06
Now working on fixing `fg`. Almost finished.

**Comment by mmstick** [comment] 2017-07-09 05:46
Still working on it. Haven't been able to fix it just yet. I'm able to notify the background thread waiting on a background process to stop waiting and quit before `fg` begins waiting on that same, exact PID, but I'm still getting an `ECHILD` error when waiting from within the `fg` function.

**Comment by mmstick** [comment] 2017-07-09 19:20
I've figured it out! I just need to perform some cleanup work, and we can mark this issue as resolved.

**Comment by mmstick** [comment] 2017-07-09 20:10
Job control is now complete for non-redox unix systems ( https://github.com/redox-os/ion/commit/8fc7729400b7ba8b2bad8e5248be61b9a39472eb ). Now we need to heavily invest into refactoring what we have and performing a few optimizations here and there.

**Closed by mmstick** 2017-07-09 20:10 UTC
Labels: enhancement, high-priority
