### ISSUE TITLE
Git URLs containing @ get mangled when executing git command

### ISSUE THREAD

**Issue by forbjok** [redox-os/ion#690] opened 2018-02-03 12:07 UTC
**Reproduction**:
Try to pass a SSH git url (ex. copy & paste from either github or bitbucket) to any command in ion.

**Expected behavior**:
To be able to clone git repositories by directly pasting the url into the terminal.

**Actual behavior**:
When an URL containing @ is passed as a commandline parameter to a command, it gets mangled by ion, causing "git clone" to hang forever due to the url it receives being incorrect.

The issue can be seen easily by `echo`ing the url:
![screenshot from 2018-02-03 11-27-03](https://user-images.githubusercontent.com/4687674/35766863-5a8184c2-08e0-11e8-9dc8-928f1ac0a982.png)

Manually adding single-quotes around the URL works around the issue.

**Build information**:
```
$ rustc -V
rustc 1.25.0-nightly (616b66dca 2018-02-02)
```
```
$ ion --version
ion 1.0.0-alpha (x86_64-unknown-linux-gnu)
rev b4ec0a2463e663db4e5f7a3f708e2451b1e00399
```

---

I'm guessing this is related to @ being used to specify arrays in scripts, and not necessarily a bug per se, but it's still a nuisance when trying to clone git repositories or do anything related to git URLs (which I imagine is a fairly common task) in ion and not an issue in other shells.

**Comment by bugabinga** [comment] 2018-02-05 18:15
@forbjok thx for explaining this behaviour. I have experienced this as well but was unsure what the issue could be.

However, it is hard to imagine a fix for this other than changing the syntax of arrays. Which seems unlikely.

Alternatively, automatically escaping pasted text will lead to issues, where people where expecting to paste in code snippets.

**Comment by mmstick** [comment] 2018-02-05 18:44
Duplicate of https://github.com/redox-os/ion/issues/538

**Closed by mmstick** 2018-02-05 18:44 UTC
